Update firebase-hosting-merge.yml

diff --git a/.github/workflows/firebase-hosting-merge.yml b/.github/workflows/firebase-hosting-merge.yml
--- a/.github/workflows/firebase-hosting-merge.yml
+++ b/.github/workflows/firebase-hosting-merge.yml
@@ -27,12 +27,31 @@ jobs:
               "description": "Mobile App Development for Juniors",
               "main": "index.js",
               "scripts": {
-                "test": "echo \"Error: no test specified\" && exit 1"
+                "test": "echo \"Error: no test specified\" && exit 1",
+                "build": "webpack --config webpack.config.js"
               },
               "author": "Raydo Matthee",
               "license": "ISC",
-              "dependencies": {}
+              "dependencies": {
+                "webpack": "^5.0.0",
+                "webpack-cli": "^4.0.0"
+              }
             }' > package.json
+          fi
+
+      - name: Create webpack.config.js if it doesn't exist
+        run: |
+          if [ ! -f webpack.config.js ]; then
+            echo 'const path = require("path");
+
+module.exports = {
+  entry: "./web-portal/js/scripts.js",
+  output: {
+    filename: "bundle.js",
+    path: path.resolve(__dirname, "web-portal/js")
+  },
+  mode: "production"
+};' > webpack.config.js
           fi
 
       - name: Install dependencies
