Update test_firebase-hosting-merge.yml

diff --git a/.github/workflows/test_firebase-hosting-merge.yml b/.github/workflows/test_firebase-hosting-merge.yml
--- a/.github/workflows/test_firebase-hosting-merge.yml
+++ b/.github/workflows/test_firebase-hosting-merge.yml
@@ -20,29 +20,32 @@ jobs:
 
       - name: Create package.json if it doesn't exist
         run: |
-           if [ ! -f package.json ]; then
-           echo '{
-           "name": "madj101",
-           "version": "1.0.0",
-           "description": "Mobile App Development for Juniors",
-           "main": "index.js",
-           "scripts": {
-           "test": "echo \"Error: no test specified\" && exit 1",
-           "build": "webpack --config webpack.config.js"
-            },
-           "author": "Raydo Matthee",
-           "license": "ISC",
-           "dependencies": {
-           "webpack": "^5.0.0",
-           "webpack-cli": "^4.0.0"
-            },
-           "devDependencies": {
-           "@babel/core": "^7.0.0",
-           "@babel/preset-env": "^7.0.0",
-           "babel-loader": "^8.0.0"
+          if [ ! -f package.json ]; then
+            cat <<'EOF' > package.json
+            {
+              "name": "madj101",
+              "version": "1.0.0",
+              "description": "Mobile App Development for Juniors",
+              "main": "index.js",
+              "scripts": {
+                "test": "echo 'Error: no test specified' && exit 1",
+                "build": "webpack --config webpack.config.js"
+              },
+              "author": "Raydo Matthee",
+              "license": "ISC",
+              "dependencies": {
+                "webpack": "^5.0.0",
+                "webpack-cli": "^4.0.0"
+              },
+              "devDependencies": {
+                "@babel/core": "^7.0.0",
+                "@babel/preset-env": "^7.0.0",
+                "babel-loader": "^8.0.0"
+              }
             }
-            }' > package.json
-           fi
+      EOF
+          fi
+
 
       - name: Create webpack.config.js if it doesn't exist
         run: |
